linters:
  enable:
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - interfacer
    - lll
    - nakedret
    - prealloc
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
    enable-all: true
  wsl:
    force-err-cuddling: true