linters:
  enable:
    - wsl
    - prealloc
    - whitespace
    - unparam
    - unconvert
    - nakedret
    - lll
    - interfacer
    - gosec
    - gomnd
    - gocritic
    - goconst
    - gochecknoinits
    - dupl
    - golint
    - goimports
    - gofmt
