linters:
  enable:
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - gosec
    - interfacer
    - lll
    - nakedret
    - prealloc
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
